{{- $data := include "server.secretData" . | trim -}}
{{- if $data -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "server.secretName" . }}
  namespace: {{ include "server.names.namespace" . }}
  labels: {{- include "server.labels.standard" . | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" (dict "value" .Values.commonAnnotations "context" $) | nindent 4 }}
  {{- end }}
type: Opaque
data: {{- $data | nindent 2 }}
{{- end }}
