apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "server.names.fullname" . }}-test
  namespace: {{ include "server.names.namespace" . }}
  labels: {{- include "server.labels.standard" . | nindent 4 }}
data:
  fullname: {{ include "server.names.fullname" . }}
  name: {{ include "server.names.name" . }}
  chart: {{ include "server.names.chart" . }}
  image: {{ include "server.image" . }}
  serviceAccountName: {{ include "server.serviceAccountName" . }}
  matchLabels: |
    {{- include "server.labels.matchLabels" . | nindent 4 }}
